server:
  port: 8763

spring:
  application:
    name: dmc-handle
  profiles:
    active: @profile@

  redis:
    host: 45.77.191.230

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762/oauth/user
#    client:
#      client-id: webapp
#      client-secret: 123456
#      access-token-uri: http://localhost:8762/oauth/token
#      scope: all

