server:
  port: 8760

spring:
  application:
    name: gateway
  profiles:
    active: @profile@

zuul:
  add-proxy-headers: true
  sensitive-headers:
  routes:
    oauth:
      stripPrefix: false
      path: /oauth/**
      serviceId: uac-handle
    uaa:
      path: /uac/**
      sensitiveHeaders:
      serviceId: uac-handle
    dmc:
      path: /dmc/**
      sensitiveHeaders:
      serviceId: dmc-handle

logging:
  level:
    root: debug
